-- =============================================================
-- V10__create_alerts_table.sql
-- =============================================================
-- Purpose:
--   Defines the system-wide alert/incident tracking layer.
--
-- Architectural Role:
--   This table acts as the central event log for all critical
--   fleet and IoT system incidents.
--
--   It captures real-time anomalies detected from:
--   - vehicle telemetry (speed, ignition, movement)
--   - device signals (offline, battery, disconnect)
--   - geofence rules (entry/exit violations)
--   - security events (theft, unauthorized access)
--
-- System Responsibilities:
--   - Stores all generated system alerts (immutable history)
--   - Tracks alert lifecycle (trigger → acknowledge → resolve)
--   - Links alerts to vehicles, devices, trips, and users
--   - Supports throttling to prevent alert spam/flooding
--   - Maintains audit-grade incident history (never deleted)
--
-- Real-Time Architecture Role:
--   Alerts are generated by backend rule engines consuming:
--   - MQTT telemetry streams
--   - trip processing pipeline
--   - geofence evaluation engine
--
-- Business Role:
--   Enables:
--   - fleet monitoring dashboards
--   - incident management workflows
--   - driver behavior enforcement
--   - security and theft detection
--
-- Data Design Strategy:
--   - Each alert represents a single system-detected event
--   - Alerts are immutable (never deleted for audit purposes)
--   - Resolution requires acknowledgement workflow
--   - Supports severity-based prioritization
--
-- Workflow Model:
--   1. Alert is triggered (system event occurs)
--   2. Alert is acknowledged (human review)
--   3. Alert is resolved (case closed)
--
-- Integrity Strategy:
--   - Ensures acknowledgment consistency (timestamps must match flags)
--   - Ensures resolution cannot occur without acknowledgment
--   - Preserves relational integrity across fleet entities
--
-- Performance Strategy:
--   - Indexed for vehicle-based dashboards
--   - Indexed for severity filtering (critical-first systems)
--   - Indexed for time-based alert timelines
--   - Composite indexes for real-time monitoring queries
--
-- Scalability Considerations:
--   Designed for high-frequency event ingestion systems
--   (IoT + streaming architectures like MQTT/Kafka pipelines)
-- =============================================================


CREATE TABLE alerts (



    -- =========================================================
    -- PRIMARY IDENTIFIER
    -- =========================================================
    -- Unique system-generated identifier for each alert.
    -- =========================================================
                        id BIGINT NOT NULL AUTO_INCREMENT,



    -- =========================================================
    -- CORE ENTITY RELATIONSHIPS
    -- =========================================================
    -- vehicle_id → vehicle that triggered the alert (required)
    -- device_id  → IoT device source of alert (optional)
    -- trip_id    → trip context for the alert (optional)
    --
    -- These links allow full traceability of incidents.
    -- =========================================================
                        vehicle_id BIGINT NOT NULL,
                        device_id BIGINT NULL DEFAULT NULL,
                        trip_id BIGINT NULL DEFAULT NULL,



    -- =========================================================
    -- HUMAN ACTION TRACKING
    -- =========================================================
    -- acknowledged_by → user who reviewed the alert
    -- resolved_by     → user who closed the alert case
    --
    -- Used for accountability and audit trails.
    -- =========================================================
                        acknowledged_by BIGINT NULL DEFAULT NULL,
                        resolved_by BIGINT NULL DEFAULT NULL,



    -- =========================================================
    -- ALERT CLASSIFICATION
    -- =========================================================
    -- Defines the type of system event that occurred.
    --
    -- Covers:
    --   - security (THEFT_DETECTED)
    --   - compliance (OVERSPEED)
    --   - geofencing (ENTRY/EXIT)
    --   - system health (DEVICE_OFFLINE)
    --   - driving behavior (HARSH_BRAKING)
    -- =========================================================
                        alert_type ENUM(
        'THEFT_DETECTED','UNAUTHORIZED_ACCESS','OVERSPEED',
        'ROUTE_DEVIATION','GEOFENCE_EXIT','GEOFENCE_ENTRY',
        'LOW_FUEL','FUEL_THEFT','BATTERY_DISCONNECT',
        'DEVICE_OFFLINE','HARSH_BRAKING','HARSH_ACCELERATION',
        'IGNITION_ON','IGNITION_OFF','SYSTEM_ERROR'
    ) NOT NULL,



    -- =========================================================
    -- SEVERITY CLASSIFICATION
    -- =========================================================
    -- Defines urgency level of the alert:
    --   CRITICAL → immediate action required
    --   HIGH     → urgent attention
    --   MEDIUM   → normal priority
    --   LOW      → minor issue
    --   INFO     → informational event
    -- =========================================================
                        severity ENUM('CRITICAL','HIGH','MEDIUM','LOW','INFO')
        NOT NULL DEFAULT 'MEDIUM',



    -- =========================================================
    -- ALERT CONTENT
    -- =========================================================
    -- title   → short summary of event
    -- message → detailed description of incident
    -- =========================================================
                        title VARCHAR(255) NOT NULL,
                        message TEXT NULL DEFAULT NULL,



    -- =========================================================
    -- LOCATION CONTEXT
    -- =========================================================
    -- Geographic coordinates where alert occurred.
    -- =========================================================
                        latitude DECIMAL(10,8) NULL DEFAULT NULL,
                        longitude DECIMAL(11,8) NULL DEFAULT NULL,



    -- =========================================================
    -- PERFORMANCE CONTEXT
    -- =========================================================
    -- speed_at_alert → vehicle speed when event occurred
    -- =========================================================
                        speed_at_alert DECIMAL(6,2) NULL DEFAULT NULL,



    -- =========================================================
    -- THRESHOLD COMPARISON DATA
    -- =========================================================
    -- threshold_value → expected limit (e.g. 100 km/h)
    -- actual_value    → measured value (e.g. 140 km/h)
    --
    -- Used for rule-based alert validation.
    -- =========================================================
                        threshold_value DECIMAL(10,2) NULL DEFAULT NULL,
                        actual_value DECIMAL(10,2) NULL DEFAULT NULL,



    -- =========================================================
    -- ACKNOWLEDGEMENT STATE
    -- =========================================================
    -- is_acknowledged → alert has been reviewed
    -- acknowledged_at → timestamp of review
    -- =========================================================
                        is_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
                        acknowledged_at TIMESTAMP NULL DEFAULT NULL,



    -- =========================================================
    -- RESOLUTION STATE
    -- =========================================================
    -- is_resolved → alert has been fully handled
    -- resolved_at → resolution timestamp
    -- resolution_notes → explanation of resolution
    -- =========================================================
                        is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
                        resolved_at TIMESTAMP NULL DEFAULT NULL,
                        resolution_notes VARCHAR(1000) NULL DEFAULT NULL,



    -- =========================================================
    -- THROTTLING / ANTI-SPAM CONTROL
    -- =========================================================
    -- cooldown_until prevents repeated alerts of same type
    -- within a short time window.
    -- =========================================================
                        cooldown_until TIMESTAMP NULL DEFAULT NULL,



    -- =========================================================
    -- EVENT TIMING
    -- =========================================================
    -- triggered_at → when system detected event
    -- created_at   → when record was inserted
    -- updated_at   → last modification timestamp
    -- =========================================================
                        triggered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                            ON UPDATE CURRENT_TIMESTAMP,



    -- =========================================================
    -- PRIMARY KEY
    -- =========================================================
                        PRIMARY KEY (id),



    -- =========================================================
    -- DATA CONSISTENCY CONSTRAINTS
    -- =========================================================

                        CONSTRAINT chk_alert_ack_ts
                            CHECK (
                                (is_acknowledged = FALSE AND acknowledged_at IS NULL)
                                    OR
                                (is_acknowledged = TRUE AND acknowledged_at IS NOT NULL)
                                ),

                        CONSTRAINT chk_alert_res_ts
                            CHECK (
                                (is_resolved = FALSE AND resolved_at IS NULL)
                                    OR
                                (is_resolved = TRUE AND resolved_at IS NOT NULL)
                                ),

                        CONSTRAINT chk_alert_resolve_requires_ack
                            CHECK (
                                is_resolved = FALSE
                                    OR (is_resolved = TRUE AND is_acknowledged = TRUE)
                                ),



    -- =========================================================
    -- FOREIGN KEY RELATIONSHIPS
    -- =========================================================

                        CONSTRAINT fk_alerts_vehicle
                            FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
                                ON UPDATE CASCADE ON DELETE RESTRICT,

                        CONSTRAINT fk_alerts_device
                            FOREIGN KEY (device_id) REFERENCES device_registry (id)
                                ON UPDATE CASCADE ON DELETE SET NULL,

                        CONSTRAINT fk_alerts_trip
                            FOREIGN KEY (trip_id) REFERENCES trips (id)
                                ON UPDATE CASCADE ON DELETE SET NULL,

                        CONSTRAINT fk_alerts_ack_by
                            FOREIGN KEY (acknowledged_by) REFERENCES users (id)
                                ON UPDATE CASCADE ON DELETE SET NULL,

                        CONSTRAINT fk_alerts_res_by
                            FOREIGN KEY (resolved_by) REFERENCES users (id)
                                ON UPDATE CASCADE ON DELETE SET NULL
);



-- =============================================================
-- INDEXING SECTION
-- =============================================================
-- Optimized for real-time monitoring and analytics workloads.
-- =============================================================

CREATE INDEX idx_alerts_vehicle_id      ON alerts (vehicle_id);
CREATE INDEX idx_alerts_type            ON alerts (alert_type);
CREATE INDEX idx_alerts_severity        ON alerts (severity);
CREATE INDEX idx_alerts_is_acknowledged ON alerts (is_acknowledged);
CREATE INDEX idx_alerts_triggered_at    ON alerts (triggered_at);

CREATE INDEX idx_alerts_vehicle_ack_sev
    ON alerts (vehicle_id, is_acknowledged, severity);

CREATE INDEX idx_alerts_throttle
    ON alerts (vehicle_id, alert_type, cooldown_until);